#!/bin/bash

set -e

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 VERSION"
fi

version=$1
name=${PWD##*/}
input=./$name.ino.pocketstar.bin
outdir=./Release
file=$name.bin

target=$outdir/$version
latest=$outdir/latest
echo moving $input to $target
mkdir -p $target/$file
cp $input $target/$file

echo Linking $target to $latest
rm -rf $latest 
cp -r $target $latest
cp ./img/thumbnail.psi $latest/$name.psi

